all: linearRegressionwith_mpi 

linearRegressionwith_mpi: linearRegressionwith_mpi.c
	mpicc -o linearRegressionwith_mpi linearRegressionwith_mpi.c -lm

clean:
	rm -f a.out *~ linearRegressionwith_mpi 


